"""Optional AI explanation layer. Product decisions remain deterministic.

Provider: DeepSeek (OpenAI-compatible chat completions).

This module only turns an already-decided outcome into natural language, and
only for explanation / discussion / general-knowledge questions. Personal
factual queries never reach a model: they are answered by ``ai_facts`` from the
verified structured facts. Nothing here writes to the deterministic engines or
changes a calculation.
"""

from __future__ import annotations

import os
import re
import time
from typing import Any, Callable, Mapping, Sequence

import requests

import ai_facts
from readiness_engine import STOP


# --------------------------------------------------------------------------- #
# Provider configuration
# --------------------------------------------------------------------------- #

DEFAULT_DEEPSEEK_MODEL = "deepseek-flash"
DEFAULT_DEEPSEEK_BASE_URL = "https://api.deepseek.com"
CHAT_COMPLETIONS_PATH = "/chat/completions"

#: Coach explanations are short, cheap and grounded. These bounds double as the
#: cost guard: a bounded prompt plus a bounded completion per request.
#: V1.3 consumer answers are shorter by design: 2–4 sentences, ~40–70 words.
MAX_OUTPUT_TOKENS = 300
REQUEST_TIMEOUT_SECONDS = 20.0
MAX_HISTORY_MESSAGES = 8
MAX_HISTORY_MESSAGE_CHARS = 500

#: Provider labels surfaced to the UI. Only ``AI_PROVIDER_LABEL`` means a model
#: wrote the wording; every other label is a deterministic answer.
AI_PROVIDER_LABEL = "DeepSeek"
PROVIDER_VERIFIED = "Verified data"
PROVIDER_INSTANT = "Instant explanation"
PROVIDER_SAFETY = "Safety rule"
PROVIDER_FALLBACK = "Rule-based fallback"

#: User-facing copy. Provider internals, HTTP status codes and tracebacks are
#: never shown in the product.
AI_UNAVAILABLE_NOTICE = "AI explanation is temporarily unavailable. The deterministic answer is shown instead."
AI_REJECTED_NOTICE = "The AI draft did not pass factual validation, so the verified deterministic answer is shown."


class DeepSeekError(RuntimeError):
    """Base class for provider failures that must degrade to the rule answer."""


class DeepSeekConfigurationError(DeepSeekError):
    """The deployment has no usable API key or provider configuration."""


class DeepSeekProviderError(DeepSeekError):
    """The provider was reachable but did not return a usable explanation."""


#: The model may explain verified facts, never decide them. Personal factual
#: questions never reach the model at all (see ``ai_facts.route_question``).
_SYSTEM_PROMPT = (
    "You are the explanation layer of a training decision-support product. "
    "The deterministic system is the source of truth for personal metrics and recommendations. "
    "Rules you must follow: never invent personal metrics or training history; never change a provided value or unit; "
    "never convert weighted working sets into days or sessions; training load is measured in points (pts) from session "
    "duration x session RPE and is not session duration; "
    "session duration is measured in minutes; never call readiness a recovery percentage; never override or replace the "
    "primary recommendation, and clearly distinguish the primary recommendation from a rule-generated alternative; "
    "if personal information is unavailable, say it is unavailable; do not infer missing health or training data; "
    "do not present a medical diagnosis, predict injury, or reveal hidden chain-of-thought. "
    # Product identity: honest about the provider, and explicit that the model did
    # not produce the deterministic recommendation.
    "If you are asked which model or provider you are, or whether you are DeepSeek, answer honestly: this explanation "
    "is generated by DeepSeek, but DeepSeek does not make the training decisions; the recommendation comes from the "
    "deterministic decision system and DeepSeek only explains verified structured facts. Never deny being DeepSeek and "
    "never claim to have produced the recommendation. "
    # Consumer answer length: decision first, then evidence, then nothing extra.
    "Be concise, clear, supportive and evidence-informed: answer in two to four short sentences and about 40 to 70 "
    "words, with the direct answer first and the most important evidence second, adding more only when the question "
    "genuinely requires it. Write for the athlete rather than for a clinician. General training and recovery concepts "
    "may be explained with general sports-science knowledge when the question is not about the user's own recorded data."
)

_diag: dict[str, Any] = {
    "request_attempted": False,
    "response_received": False,
    "generation_completed": False,
    "validation_accepted": False,
    "provider_used": PROVIDER_FALLBACK,
    "stage": None,
    "last_validation_reason": "Not requested",
    "prompt_tokens": None,
    "completion_tokens": None,
}
_last_model_error: str | None = None
_last_generation_seconds: float | None = None


# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #


def _setting(secrets: Mapping[str, Any] | None, name: str) -> str:
    try:
        secret = secrets.get(name, "") if secrets is not None else ""
    except Exception:
        secret = ""
    return str(secret or os.getenv(name, "")).strip()


def _is_true(value: str) -> bool:
    return value.casefold() in {"1", "true", "yes", "on"}


def deepseek_api_key(secrets: Mapping[str, Any] | None = None) -> str:
    """Streamlit secrets take priority, then the environment variable."""
    return _setting(secrets, "DEEPSEEK_API_KEY")


def deepseek_model_name(secrets: Mapping[str, Any] | None = None) -> str:
    return _setting(secrets, "DEEPSEEK_MODEL") or DEFAULT_DEEPSEEK_MODEL


def deepseek_base_url(secrets: Mapping[str, Any] | None = None) -> str:
    return (_setting(secrets, "DEEPSEEK_BASE_URL") or DEFAULT_DEEPSEEK_BASE_URL).rstrip("/")


def ai_coach_enabled(secrets: Mapping[str, Any] | None = None) -> bool:
    """The explanation layer is opt-in: no key means deterministic answers only."""
    if _is_true(_setting(secrets, "DISABLE_AI_COACH")) or _is_true(_setting(secrets, "DISABLE_EMBEDDED_LLM")):
        return False
    return bool(deepseek_api_key(secrets))


def _redact(text: str) -> str:
    """Never let a credential reach a log line, notice or diagnostics panel."""
    return re.sub(r"sk-[A-Za-z0-9_\-]{4,}", "sk-***", text)


def _build_provider(secrets: Mapping[str, Any] | None = None) -> "DeepSeekCoachProvider":
    return DeepSeekCoachProvider(
        api_key=deepseek_api_key(secrets),
        model=deepseek_model_name(secrets),
        base_url=deepseek_base_url(secrets),
    )


# --------------------------------------------------------------------------- #
# Provider
# --------------------------------------------------------------------------- #


class DeepSeekCoachProvider:
    """Minimal OpenAI-compatible chat-completions client.

    Deliberately dependency-light: one HTTPS POST built on ``requests``, which
    is already a Streamlit dependency. ``transport`` exists so tests can inject
    a fake callable instead of contacting the provider.
    """

    def __init__(self, api_key: str, model: str = DEFAULT_DEEPSEEK_MODEL,
                 base_url: str = DEFAULT_DEEPSEEK_BASE_URL,
                 timeout: float = REQUEST_TIMEOUT_SECONDS,
                 transport: Callable[..., Any] | None = None) -> None:
        self.api_key = api_key
        self.model = model
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout
        self._transport = transport

    @property
    def endpoint(self) -> str:
        return f"{self.base_url}{CHAT_COMPLETIONS_PATH}"

    @property
    def configured(self) -> bool:
        return bool(self.api_key)

    def build_payload(self, messages: Sequence[Mapping[str, str]]) -> dict[str, Any]:
        """Structured request. Thinking is disabled explicitly, never by default."""
        return {
            "model": self.model,
            "messages": [{"role": str(item.get("role")), "content": str(item.get("content", ""))} for item in messages],
            "stream": False,
            "temperature": 0.3,
            "max_tokens": MAX_OUTPUT_TOKENS,
            # Non-thinking mode: the Coach explains a decision the deterministic
            # engine already made, so long hidden reasoning is neither wanted
            # nor needed.
            "thinking": {"type": "disabled"},
        }

    def build_headers(self) -> dict[str, str]:
        return {"Authorization": f"Bearer {self.api_key}", "Content-Type": "application/json"}

    def complete(self, messages: Sequence[Mapping[str, str]]) -> str:
        if not self.configured:
            raise DeepSeekConfigurationError("DEEPSEEK_API_KEY is not configured")
        payload = self.build_payload(messages)
        post = self._transport or requests.post
        try:
            response = post(self.endpoint, headers=self.build_headers(), json=payload, timeout=self.timeout)
        except requests.exceptions.Timeout as exc:
            raise DeepSeekProviderError("The AI provider did not respond in time") from exc
        except requests.exceptions.RequestException as exc:
            raise DeepSeekProviderError("The AI provider could not be reached") from exc
        _diag["response_received"] = True
        status = int(getattr(response, "status_code", 200))
        if status >= 400:
            # Deliberately does not echo the provider body: it can contain
            # request metadata that must not be surfaced or persisted.
            raise DeepSeekProviderError(f"The AI provider returned HTTP {status}")
        try:
            body = response.json()
        except ValueError as exc:
            raise DeepSeekProviderError("The AI provider returned an unreadable response") from exc
        if not isinstance(body, Mapping):
            raise DeepSeekProviderError("The AI provider returned an unexpected response shape")
        usage = body.get("usage") or {}
        if isinstance(usage, Mapping):
            _diag["prompt_tokens"] = usage.get("prompt_tokens")
            _diag["completion_tokens"] = usage.get("completion_tokens")
        choices = body.get("choices") or []
        text = ""
        if choices and isinstance(choices[0], Mapping):
            message = choices[0].get("message") or {}
            if isinstance(message, Mapping):
                text = str(message.get("content") or "").strip()
        if not text:
            raise DeepSeekProviderError("The AI provider returned an empty explanation")
        return text


# --------------------------------------------------------------------------- #
# Diagnostics
# --------------------------------------------------------------------------- #


def ai_diagnostics(secrets: Mapping[str, Any] | None = None) -> dict[str, Any]:
    """Developer-only panel. States whether a key exists; never prints it."""
    return {
        "Provider": AI_PROVIDER_LABEL,
        "Model": deepseek_model_name(secrets),
        "Base URL": deepseek_base_url(secrets),
        "API key": "Configured" if deepseek_api_key(secrets) else "Not configured",
        "Credential source": "Streamlit secrets, then environment variable",
        "Explanation layer": "Enabled" if ai_coach_enabled(secrets) else "Disabled",
        "Request attempted": "Yes" if _diag["request_attempted"] else "No",
        "Response received": "Yes" if _diag["response_received"] else "No",
        "Generation completed": "Yes" if _diag["generation_completed"] else "No",
        "Validation accepted": "Yes" if _diag["validation_accepted"] else "No",
        "Active provider": _diag["provider_used"],
        "Prompt tokens": _diag["prompt_tokens"] if _diag["prompt_tokens"] is not None else "—",
        "Completion tokens": _diag["completion_tokens"] if _diag["completion_tokens"] is not None else "—",
        "Response time": f"{_last_generation_seconds:.2f}s" if _last_generation_seconds is not None else "—",
        "Last error stage": _diag.get("stage") or "—",
        "Last validation reason": _diag.get("last_validation_reason", "Not requested"),
        "Last exception": _last_model_error or "None",
    }


def ai_engine_status(secrets: Mapping[str, Any] | None = None) -> str:
    if _is_true(_setting(secrets, "DISABLE_AI_COACH")) or _is_true(_setting(secrets, "DISABLE_EMBEDDED_LLM")):
        return "AI explanations are disabled for this deployment · deterministic Coach is ready"
    if deepseek_api_key(secrets):
        return f"{AI_PROVIDER_LABEL} explanation layer is configured"
    return "Deterministic Coach fallback is ready · set DEEPSEEK_API_KEY to enable AI explanations"


# --------------------------------------------------------------------------- #
# Deterministic answers
# --------------------------------------------------------------------------- #


def validate_llm_response(text: str, readiness_status: str, primary_workout: str | None = None, question: str = "", recommendation: Mapping[str, Any] | None = None) -> tuple[bool, str]:
    """Reject only an explicit contradiction of the overall status."""
    found = re.findall(r"(?:overall\s+)?readiness\s+(?:status\s+)?(?:is|:)?\s*(green|amber|red)", text.casefold())
    contradictory = [value.upper() for value in found if value.upper() != readiness_status.upper()]
    if contradictory:
        return False, f"Explicit overall readiness contradiction: {contradictory[0]}"
    if primary_workout:
        claims = re.findall(r"(?:primary recommendation|today'?s (?:approved )?workout)\s+(?:is|:)\s*([^\n.]+)", text, flags=re.IGNORECASE)
        if claims and all(primary_workout.casefold() not in claim.casefold() for claim in claims):
            return False, "The response replaced the recorded primary recommendation."
    q = question.casefold()
    if "what is rir" in q and "repetitions in reserve" not in text.casefold():
        return False, "The response did not correctly define RIR."
    if recommendation and any(term in q for term in ("sets this week", "how many back sets", "how many chest sets", "how many leg sets")):
        mentioned = [group for group in recommendation.get("weekly_exposure", {}) if group.casefold() in q]
        for group in mentioned:
            expected = f"{float(recommendation['weekly_exposure'][group]):g}"
            if expected not in text:
                return False, f"The response did not preserve the recorded {group} exposure."
    if primary_workout and ("why" in q and any(term in q for term in ("recommend", "workout", primary_workout.casefold()))) and primary_workout.casefold() not in text.casefold():
        return False, "The contextual explanation did not identify the recorded primary recommendation."
    if primary_workout and any(term in q for term in ("instead", "alternative", "swap")):
        lower = text.casefold()
        if primary_workout.casefold() not in lower or "alternative" not in lower:
            return False, "The response did not distinguish the primary recommendation from an alternative."
    return True, "No explicit overall readiness contradiction"


def rule_based_answer(question: str, profile: Mapping[str, Any], assessment: Mapping[str, Any], recommendation: Mapping[str, Any] | None = None) -> str:
    q = question.casefold()
    status = assessment["overall_readiness"]
    contributors = "; ".join(assessment.get("key_contributors", [])[:3]) or "no material adverse contributors were detected"
    if status == STOP:
        flags = ", ".join(assessment.get("safety_flags", [])) or "a current safety concern"
        return f"Safety mode is active because you selected {flags}. Normal workout guidance is disabled: pause demanding training and seek appropriate assessment for acute or concerning symptoms."
    if any(term in q for term in ("chest pain", "fainting", "severe shortness", "acute injury", "fever", "neurological")):
        return "This Coach cannot assess serious symptoms. Stop demanding training and seek appropriate medical assessment; seek urgent local help if symptoms are severe or worsening."
    # Personal facts are answered from the structured fact layer, never from keywords
    # or model output (hotfix AI-01).
    facts = ai_facts.build_personal_facts(profile, assessment, recommendation)
    route = ai_facts.route_question(question, (), facts)
    if route.kind == "PERSONAL_FACT":
        return ai_facts.grounded_answer(route, facts)
    if route.kind == "UNRESOLVED_PERSONAL":
        return ai_facts.CLARIFICATION
    if route.kind == "CORRECTION":
        return ai_facts.correction_answer(None, facts, None)
    if "capital of japan" in q or "capital of" in q:
        return "This Coach is designed for training, readiness and recovery questions."
    if q.strip() in {"what is rir", "what's rir", "define rir"} or "what is rir" in q:
        return "RIR means repetitions in reserve: how many good repetitions you estimate you could still perform at the end of a set. For example, 2 RIR means stopping when you believe about two quality repetitions remain."
    if "what is rpe" in q or "what's rpe" in q:
        return "RPE is a perceived-effort scale. Session-RPE is commonly recorded from 1 to 10 after training and can be combined with duration to estimate internal load. It is a practical monitoring measure, not a diagnosis."
    if "failure" in q:
        return "You do not need to take every set to failure. Leaving repetitions in reserve can preserve technique and manage fatigue; the appropriate effort depends on the exercise, goal and today's readiness."
    if "chest twice" in q or "twice a week" in q:
        return "Training chest twice per week can be a reasonable way to distribute weekly volume when total sets, exercise quality and recovery are managed. Your current weekly exposure and today's recommendation should guide whether another chest session is useful today."
    if "deload" in q:
        return "A deload is a planned period of lower training demand, often used when fatigue is accumulating or performance and motivation are persistently affected. The exact format should fit the person's context rather than a fixed universal schedule."
    if recommendation and any(term in q for term in ("how many", "sets this week", "trained this week", "this week")):
        exposure = recommendation.get("weekly_exposure", {})
        for group, value in exposure.items():
            if group.casefold() in q or (group == "Hamstrings / Glutes" and any(term in q for term in ("hamstring", "glute"))):
                return f"You have logged **{value:g} effective {group.lower()} sets** in the current seven-day window. Direct sets count as 1.0 and mapped indirect sets as 0.5, so this is a transparent exposure estimate rather than an exact stimulus measure."
    if any(term in q for term in ("workout", "train today", "back", "legs", "cardio", "swap", "recommend", "recent training", "rest")) and recommendation:
        primary = recommendation["primary"]
        rationale = " ".join(recommendation.get("rationale", [])[:3])
        alternatives = {item["name"]: item for item in recommendation.get("alternatives", [])}
        if "cardio" in q and primary.get("training_type") != "Aerobic":
            aerobic = next((item for item in recommendation.get("alternatives", []) if item.get("training_type") == "Aerobic"), None)
            if aerobic:
                return f"**{primary['name']} remains the primary recommendation.** {aerobic['name']} is a listed rule-generated alternative at {aerobic['intensity']}; choose it only as an alternative, not as a silent replacement. {rationale}"
            return f"**{primary['name']} remains the primary recommendation.** Cardio is not one of today's two listed alternatives. If you independently choose easy aerobic work, treat it as a lower-demand substitute and respect the current avoid-today and safety guidance."
        if "leg" in q and primary["name"] != "Legs":
            permitted = alternatives.get("Legs")
            if permitted:
                return f"**{primary['name']} remains the primary recommendation.** Legs are available as a rule-generated alternative, but consider today's local soreness, recent lower-body work and the listed avoid-today guidance. {rationale}"
            return f"**{primary['name']} remains the primary recommendation.** Legs are not a current rule-generated alternative. {rationale} Check the avoid-today list and choose a lower-conflict option."
        return f"Today's primary recommendation is **{primary['name']}** ({recommendation['intensity']}, {recommendation['duration']}). {rationale} Alternatives remain clearly labelled and do not replace the primary recommendation."
    if any(term in q for term in ("why", "amber", "red", "green", "baseline", "hrv")):
        return f"Your readiness is **{status}**. The main context is {contributors}. This comparison uses {profile['name']}'s own history rather than universal HRV or resting-heart-rate cut-offs."
    if any(term in q for term in ("hard", "intensity", "session")):
        return f"For the current **{status}** status: " + " ".join(assessment["decision_support"][:2])
    return "Ask me about readiness, training volume, RIR/RPE, recent completed sessions, today's recommendation or recovery."


def get_instant_response(question: str, profile: Mapping[str, Any], assessment: Mapping[str, Any], recommendation: Mapping[str, Any] | None = None) -> tuple[str, str, None]:
    provider = PROVIDER_SAFETY if assessment["overall_readiness"] == STOP else PROVIDER_INSTANT
    return rule_based_answer(question, profile, assessment, recommendation), provider, None


# --------------------------------------------------------------------------- #
# Model call
# --------------------------------------------------------------------------- #


def build_request_messages(question: str, profile: Mapping[str, Any], assessment: Mapping[str, Any],
                           recommendation: Mapping[str, Any], history: Sequence[Mapping[str, str]] = ()) -> list[dict[str, str]]:
    """Minimised structured context. Never the full local database."""
    facts = ai_facts.build_personal_facts(profile, assessment, recommendation)
    context = (f"Profile: {profile['name']}; goal: {profile.get('training_goal', 'General Fitness')}; "
               f"training level: {profile.get('training_level', 'Not recorded')}; "
               f"preferred split: {profile.get('training_split_preference', 'No Preference')}.\n"
               + ai_facts.facts_for_prompt(facts))
    messages: list[dict[str, str]] = [{"role": "system", "content": _SYSTEM_PROMPT}]
    for message in list(history)[-MAX_HISTORY_MESSAGES:]:
        if message.get("role") in {"user", "assistant"}:
            messages.append({"role": message["role"], "content": str(message.get("content", ""))[:MAX_HISTORY_MESSAGE_CHARS]})
    messages.append({"role": "user",
                     "content": f"Verified structured personal facts (the only permitted source of personal numbers):\n{context}\nQuestion: {question}"})
    return messages


def _generate(question: str, profile: Mapping[str, Any], assessment: Mapping[str, Any],
              recommendation: Mapping[str, Any], history: Sequence[Mapping[str, str]] = (),
              secrets: Mapping[str, Any] | None = None, provider: "DeepSeekCoachProvider | None" = None) -> str:
    provider = provider or _build_provider(secrets)
    messages = build_request_messages(question, profile, assessment, recommendation, history)
    _diag["stage"] = "GENERATION"
    return provider.complete(messages)


# --------------------------------------------------------------------------- #
# Entry point
# --------------------------------------------------------------------------- #


def get_ai_response(question: str, profile: Mapping[str, Any], assessment: Mapping[str, Any], recommendation: Mapping[str, Any], history: Sequence[Mapping[str, str]] = (), secrets: Mapping[str, Any] | None = None) -> tuple[str, str, str | None]:
    """Answer contextually while deterministic engines retain decision authority."""
    facts = ai_facts.build_personal_facts(profile, assessment, recommendation)
    route = ai_facts.route_question(question, history, facts)
    _diag["last_route"] = route.as_trace()
    if assessment["overall_readiness"] == STOP:
        return rule_based_answer(question, profile, assessment, recommendation), PROVIDER_SAFETY, None
    if route.kind == "SAFETY":
        return rule_based_answer(question, profile, assessment, recommendation), PROVIDER_SAFETY, None
    if route.kind == "PERSONAL_FACT":
        # Deterministic layer answers; the model is not consulted, so it cannot
        # invent a number, unit or period for the user's own data.
        return ai_facts.grounded_answer(route, facts), PROVIDER_VERIFIED, "Answered from your recorded data. No model wording was used."
    if route.kind == "UNRESOLVED_PERSONAL":
        return ai_facts.CLARIFICATION, PROVIDER_VERIFIED, "The question could not be mapped to a supported personal metric, so no model was used."
    if route.kind == "CORRECTION":
        previous_route = ai_facts.route_question(route.previous_question or "", (), facts)
        if previous_route.kind != "PERSONAL_FACT":
            # A challenge can follow another challenge ("Are you sure?" after a
            # correction, or after a non-factual question). Walk back to the most
            # recent question that asked for a verifiable personal fact.
            for message in reversed(list(history)):
                if message.get("role") != "user":
                    continue
                candidate = ai_facts.route_question(str(message.get("content", "")), (), facts)
                if candidate.kind == "PERSONAL_FACT":
                    previous_route = candidate
                    break
        previous_answer = next((str(message.get("content", "")) for message in reversed(list(history)) if message.get("role") == "assistant"), None)
        answer = ai_facts.correction_answer(previous_route if previous_route.kind == "PERSONAL_FACT" else None, facts, previous_answer)
        return answer, PROVIDER_VERIFIED, "Your previous answer was re-checked against your recorded data."
    # Only explanation / discussion / general questions continue past this point.
    if _is_true(_setting(secrets, "DISABLE_AI_COACH")) or _is_true(_setting(secrets, "DISABLE_EMBEDDED_LLM")):
        return rule_based_answer(question, profile, assessment, recommendation), PROVIDER_INSTANT, "AI explanations are disabled for this deployment, so the deterministic answer is shown."
    if not deepseek_api_key(secrets):
        return rule_based_answer(question, profile, assessment, recommendation), PROVIDER_INSTANT, AI_UNAVAILABLE_NOTICE
    try:
        started = time.monotonic()
        _diag["request_attempted"] = True
        _diag["response_received"] = False
        _diag["generation_completed"] = False
        _diag["validation_accepted"] = False
        _diag["stage"] = "GENERATION"
        explanation = _generate(question, profile, assessment, recommendation, list(history)[-MAX_HISTORY_MESSAGES:], secrets)
        global _last_generation_seconds
        _last_generation_seconds = time.monotonic() - started
        _diag["generation_completed"] = True
        approved = recommendation["primary"]["name"]
        accepted, validation_reason = validate_llm_response(explanation, str(assessment["overall_readiness"]), approved, question, recommendation)
        if accepted:
            accepted, validation_reason = ai_facts.guard_llm_response(explanation, facts, question, route)
        if accepted and route.kind == "EXPLANATION":
            accepted, validation_reason = ai_facts.guard_explanation_grounding(explanation, facts)
        if not accepted:
            _diag["stage"] = "VALIDATION"
            _diag["last_validation_reason"] = validation_reason
            raise ValueError(validation_reason)
        _diag["validation_accepted"] = True
        _diag["provider_used"] = AI_PROVIDER_LABEL
        _diag["last_validation_reason"] = validation_reason
        return explanation, AI_PROVIDER_LABEL, None
    except Exception as exc:
        global _last_model_error
        _last_model_error = _redact(f"{type(exc).__name__}: {str(exc)[:280]}")
        _diag["provider_used"] = PROVIDER_FALLBACK
        _diag["stage"] = _diag.get("stage") or "GENERATION"
        if _diag.get("stage") != "VALIDATION":
            _diag["last_validation_reason"] = "Fallback retained the canonical deterministic answer."
        notice = AI_REJECTED_NOTICE if _diag.get("stage") == "VALIDATION" else AI_UNAVAILABLE_NOTICE
        return rule_based_answer(question, profile, assessment, recommendation), PROVIDER_INSTANT, notice
